# Generated by Django 3.1.4 on 2021-03-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_auto_20210328_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concern',
            name='complete',
        ),
    ]
