# Generated by Django 3.1.4 on 2021-03-29 22:28

import certificate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_auto_20210329_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=certificate.models.upload_path),
        ),
    ]
