# Generated by Django 3.1.4 on 2021-03-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0006_auto_20210330_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='discription1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='discription2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='discription',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
